urlshortener/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about')
]

urlshortener/urlapp/urls.py
from . import views
from django.urls import path

app_name = 'urlapp'

urlpatterns = [
    path('', views.MakeUrl.as_view(), name='make_url'),
    path('<slug:urlslug>/', views.redirect_url, name='redirect_url')
]

urlshortener/urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', include('urlapp.urls')),
    path('', include('mainapp.urls'))
]

urlshortener/mainapp/models.py
from django.db import models

# Create your models here.

urlshortener/urlapp/models.py
from email.policy import default
import imp
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

# Create your models here.
class ShortenedUrl(models.Model):
    """
    A modelfor shortened urls
    -------------------------
    slug : The slug for shortened url
    target_url : The url that user will be redirected to
    link: The final shortened url
    date: The time that object was created.
    """
    slug = models.SlugField(unique=True, null=True)
    target_url = models.URLField(default='http://www.google.com')
    link = models.URLField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.link}'

@receiver(post_save, sender=ShortenedUrl)
def create_url_link(sender, instance, created, **kwargs):
    """
    Creates final link from slug and current site domain
    """
    if created:
        instance.link = f'http://{settings.SITE_DOMAIN}/url/{instance.slug}'
        instance.save()

urlshortener/mainapp/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'mainapp/home.html')

def about(request):
    return render(request, 'mainapp/about.html')

urlshortener/urlapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import ShortenedUrl
from django.contrib.sites.shortcuts import get_current_site
from django.utils.text import slugify
# Create your views here.

class MakeUrl(View):
    """
    Creates ShortenedUrl object from posted target_url and slug arguments.
    ---------------------------------------------------------------------
    target_url : The url that the user will be redirected to.
    slug : The slug used in shortened url.
    """
    def get(self, request):
        return render(request, 'urlapp/make_url.html', {'domain': get_current_site(self.request).domain})

    def post(self,request):
        target_url = request.POST.get('target_url')
        slug = slugify(request.POST.get('slug'))

        #check if the requested url slug already exists or not
        if ShortenedUrl.objects.filter(slug=slug).exists():
            error = 'a url with this name already exists. try using another one'
            return render(request, 'urlapp/make_url.html', {'domain': get_current_site(self.request).domain,'error': error})
        
        shortened_url = ShortenedUrl.objects.create(target_url = target_url, slug = slug)
        shortened_url.save()
        return render(request, 'urlapp/show_url.html', {'shortened_url': shortened_url.link})

 
def redirect_url(request, urlslug):
    """ redirects user to target url. """
    url = ShortenedUrl.objects.get(slug = urlslug)
    return redirect(url.target_url)

urlshortener/templates/base/base.html
{# 
    the base template for all pages    
#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/bootstrap.min.js'%}" ></script>
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js'%}" ></script>
    <script src="{% static 'bootstrap/popper.min.js'%}" ></script>
</head>
<body>
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

urlshortener/templates/base/navbar.html
{# The navbar #}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'mainapp:home' %}">Home </a>
        <a class="nav-item nav-link" href="{% url 'mainapp:about' %}">About</a>
        <a class="nav-item nav-link" href="{% url 'urlapp:make_url' %}">Make a shortened url</a>
      </div>
    </div>
  </nav>

urlshortener/templates/mainapp/about.html
{% extends 'base/base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<div class="card" style="margin: 30px 30px 30px;">
    <div class="card-body">
        <h1>UrlShortener can help you turn long links into short urls</h1><br>
        <button type="button" class="btn btn-primary" onclick="document.location = {% url 'urlapp:make_url' %}">Get started</button>
    </div>
</div>
{% endblock %}

urlshortener/templates/mainapp/home.html
{% extends 'base/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="card" style="margin: 30px 30px 30px;">
    <div class="card-body">
        <h1>Welcome to UrlShortener</h1><br>
        <button type="button" class="btn btn-primary" onclick="document.location = {% url 'mainapp:about' %}">Learn more</button>
    </div>
</div>
{% endblock %}

urlshortener/templates/urlapp/make_url.html
{% extends 'base/base.html' %}
{% block title %}Create your shortened url{% endblock %}
{% block content %}
<div class="card" style="width: 90%; border-radius: 30px; margin: 50px 100px 100px;;">
    <div class="card-body">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="post">
            <div class="mb-3">
                <label class="form-label">Target url</label>
                <input type="text" class="form-control" name="target_url" placeholder="https://example.com/">
                <div id="emailHelp" class="form-text">The url you want to shorten</div>
            </div>
            <div class="mb-3">
                <label class="form-label">The name of your url</label>
                <input type="text" class="form-control" name="slug" placeholder="http://{{ domain }}/url/<Url Name>">
            </div>
            <button type="submit" class="btn btn-primary">Create url</button>
            {% csrf_token %}
        </form>
    </div>
</div>
<!--input type="text" name="target_url" placeholder="Target url"-->
    <!--input type="text" name="slug" placeholder="Slug"-->

{% endblock %}

urlshortener/templates/urlapp/show_url.html
{% extends 'base/base.html' %}
{% block title %}Url was shortened successfully{% endblock %}
{% block content %}
<div class="card" style="margin: 30px 30px 30px;">
    <div class="card-body">
        <h1>Url was shortened successfully</h1><br>
        <h1>shortened url is: <a href="{{ shortened_url }}">{{ shortened_url }}</a></h1>
    </div>
</div>
{% endblock %}